{% set name = "knitty" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb3d48e9dbdb742ca7747a070dc5e0daaa3c8815550ab808a0587fb72d79ee15

build:
  noarch: python
  number: 0
  entry_points:
    - knitty = knitty.knitty:main
    - pre-knitty = knitty.pre_knitty:main
    - post-knitty = knitty.post_knitty:cli
    - knotr = knitty.stitch.cli:cli
    - knotedown = knitty.notedown.main:app
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - panflute >=1.11.2
    - pandoc >=2.4
    - jupyter_core
    - traitlets
    - ipython
    - jupyter_client
    - nbconvert
    - pandocfilters
    - pypandoc
    - click
    - psutil
    - nbformat
    - pandoc-attributes
    - pyyaml

test:
  imports:
    - knitty
    - knitty.tools
    - knitty.notedown
    - knitty.stitch
  commands:
    - knitty --help
    - pre-knitty --help
    - post-knitty --help
    - knotr --help
    - knotedown --help

about:
  home: https://github.com/kiwi0fruit/knitty
  license: "GPL2+"
  license_family: GPL2
  license_file: LICENSE
  summary: "Inrterface wrapper for Stitch/Knotr: reproducible report generation tool via Jupyter, Pandoc and Markdown. Export to Jupyter notebook via Notedown."
  doc_url: https://github.com/kiwi0fruit/knitty
  dev_url: https://github.com/kiwi0fruit/knitty

extra:
  recipe-maintainers:
    - kiwi0fruit
