{% set name = "knitty" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 575db25655298a4bd2dd2ee773c93aa077abe577772558eb144ead050bd7fab6

build:
  noarch: python
  number: 0
  entry_points:
    - knitty = knitty.knitty:main
    - pre-knitty = knitty.pre_knitty:main
    - knotedown = knitty.notedown.main:app
    - pandoc-filter-arg = knitty.pandoc_filter_arg.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - panflute >=1.11.2
    - jupyter_core
    - traitlets
    - ipython
    - jupyter_client
    - nbconvert >=5.4.1
    - pandocfilters
    - py-pandoc >=2.6
    - click
    - psutil
    - nbformat
    - pandoc-attrs
    - pyyaml
    - shutilwhich-cwdpatch >=0.1.0

test:
  imports:
    - knitty
    - knitty.api
    - knitty.tools
    - knitty.notedown
    - knitty.stitch
    - knitty.pandoc_filter_arg
  commands:
    - knitty --help
    - pre-knitty --help
    - knotedown --help
    - pandoc-filter-arg --help

about:
  home: https://github.com/kiwi0fruit/knitty
  license: "GPL2+"
  license_family: GPL2
  license_file: LICENSE
  summary: "Reproducible report generation tool via Jupyter, Pandoc and Markdown. Contains fork of the Notedown."
  doc_url: https://github.com/kiwi0fruit/knitty
  dev_url: https://github.com/kiwi0fruit/knitty

extra:
  recipe-maintainers:
    - kiwi0fruit
