travis:
  secure:
    BINSTAR_TOKEN: pbBzGTd6X+o4gn4jgKNxtl3LZrtGv+Ws5jLUgPdakj6E1gG5CMGEFqKQhSyflVLZ3nYTfzVDcijrKojevScZbMd2K9m1gfnn1G5Pear50vcmjVCC7yTo7KdPq4or+KFqemvg9N8KAswsxlNUNBLSO3LgRnGAAwDziH7c6KLqC/TO6jGEsmN5UXQyOvNzaRFVQQCbRqWhj2PNVKktPX7E4g+AFRygr7bwIkzDRJrwt1MSHKsgYxYMDxPrLriGPVc/O7bOw9GNuUnfVfgBlYKXJkaJgJOtAj2K2v8qtRWtDVcdLk7LP7L5lYFSGXok9tA7xijmRq9X5DCQGs3z+mzpG12yDuoBQxlEPRPnTyAvmOd/33bDQf6GnRhfxsTsj7u/MfVa5ceP0SerF6NG78/19kGEaMhB0SvYANc9k666clVn/dAMbTNLIbKLyqYFQ/1ukTJajk/TUtjYa2SLSe+YLDzA99ClPyStXFvWbzoEzJfFDV1ifLdrMQ2vJjwEh3ONScfji/QKjatrqwgia34GyybBMYS1arDE6b5BfQBGCen+YOZCqcTX1JwaK6jHdmfo6A06X8IqC7YHBxkVnPPgNdNaEQcP4frn2VwwEI/m++TNNDVIx30TIsKDWg4UphnaBxwYRHT+F+hLnG68EokthHbYUUe6JtkK9brrsJNNT4A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
